## Aula 03
Introdução a Aula 03
- Biblioteca Pandas
- Biblioteca Numpy

````pyton
print ("Olá mundo")
````

1. Conhecendo a biblioteca
2. Executando os comandos

In [ ]:
#Apelido
import pandas as pd
import numpy as np

In [8]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]


array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

[  30   25   42 1000]

In [11]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nome_produtos = ["Pastel", "Caçulinha", "Refrigerante","Combos"]


array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
for nome, preco in zip(nome_produtos,faturamento):
    print(f"{nome} : {preco}")

Pastel : 30
Caçulinha : 25
Refrigerante : 42
Combos : 1000

### Exercício de fixação
- Criar umas lista que irá possuir 10 nomes de produtos.
- Criar uma lista que irá possuir o preço de custo (atacado).
- Criar uma lista que irá possuir o preço de venda (varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [20]:
Nome_produtos = ["Base líquida", "Corretivo", "Batom líquido", "Lápis de olho", "Hidratante corporal", "Protetor solar", "Perfume Kaiak","Máscara de cílios", "Creme de barbear", "Hidratante para lábios" ]
Preco_custo = [42,35,30,25,50,55,120,42,40,32]
Preco_venda = [82,68,60,50,90,100,200,84,80,64]

array_preco_custo = np.array(Preco_custo)
array_preco_venda = np.array(Preco_venda)

Lucro = array_preco_venda - array_preco_custo
for name, preco in zip(Nome_produtos,Lucro):
    print(f"Lucro de produtos vendidos: {name}:{preco}")

Lucro de produtos vendidos: Base líquida:40
Lucro de produtos vendidos: Corretivo:33
Lucro de produtos vendidos: Batom líquido:30
Lucro de produtos vendidos: Lápis de olho:25
Lucro de produtos vendidos: Hidratante corporal:40
Lucro de produtos vendidos: Protetor solar:45
Lucro de produtos vendidos: Perfume Kaiak:80
Lucro de produtos vendidos: Máscara de cílios:42
Lucro de produtos vendidos: Creme de barbear:40
Lucro de produtos vendidos: Hidratante para lábios:32

Pandas

In [3]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv") #r ignora barras invertidas
df.head() #Por padrão ele exibe as 5 primeiras informações. Head é uma função, precisa escrever dentro do parentese.

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [25]:
df.tail() #Exibe as 5 últimas informações.

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
df.shape #Exibe a qtdd de colunas e linhas. Shape é um método, não precisa de parentese. Dimensões da tabela/tamanho.

(40, 6)

In [ ]:
df.columns #Exibe as colunas da base de dados.

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     object
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), object(1)
memory usage: 2.0+ KB

In [29]:
df.duplicated().sum() #Contar valores duplicados

np.int64(0)

In [30]:
df.isna().sum() #Contar valores nulos.

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [31]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [4]:
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [5]:
#Combinando filtros
df[["id_registro","temperatura_c","falha"]]

    id_registro  temperatura_c  falha
0             1          72.62      0
1             2          81.65      0
2             3          68.87      0
3             4          66.84      0
4             5          66.23      0
5             6          64.79      0
6             7          85.02      1
7             8          60.31      0
8             9          75.84      0
9            10          68.38      1
10           11          76.31      0
11           12          74.79      0
12           13          76.31      0
13           14          63.28      0
14           15          64.98      0
15           16          81.48      0
16           17          79.62      1
17           18          69.80      0
18           19          77.16      0
19           20          73.30      1
20           21          79.77      0
21           22          71.76      0
22           23          74.16      0
23           24          74.69      1
24           25          74.03      1
25           26          75.96      0
26           27          60.80      0
27           28          69.37      1
28           29          70.28      0
29           30          73.53      0
30           31          63.59      1
31           32          68.91      0
32           33          77.62      1
33           34          73.32      1
34           35          78.24      0
35           36          68.47      0
36           37          75.62      1
37           38          78.50      0
38           39          76.19      1
39           40          68.64      0

In [6]:
#Criar uma nova coluna relacionando dados
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"Temperatura Alta", "Temperatura Baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,Temperatura Baixa
1,2,Usinagem,81.65,34.08,128,0,Temperatura Alta
2,3,Usinagem,68.87,39.44,159,0,Temperatura Baixa
3,4,Usinagem,66.84,34.52,98,0,Temperatura Baixa
4,5,Usinagem,66.23,31.57,94,0,Temperatura Baixa

Subir a base de dados
- Mostrar os 5 primeiros registros
- Mostrar os 5 últimos 
- Mostrar o tamanho
- Mostrar a descrição

In [41]:
df = pd.read_csv(r".\data\dataset_techshop_vendas.csv")
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [ ]:
df.tail() #5 ÚLTIMOS

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [ ]:
df.shape #TAMANHO

(800, 7)

In [ ]:
df.describe() #DESCRIÇÃO

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000