 N-gramas(n-grams)

In [7]:
frase = "Ele sabia que eu sabia trabalhar com IA e sabia que eu estava estudando tecnologia sabia trabalhar"

In [8]:
#O split transforma a frase em uma lista.
palavras = frase.split()
palavras

['Ele',
 'sabia',
 'que',
 'eu',
 'sabia',
 'trabalhar',
 'com',
 'IA',
 'e',
 'sabia',
 'que',
 'eu',
 'estava',
 'estudando',
 'tecnologia',
 'sabia',
 'trabalhar']

In [10]:
import pandas as pd
tabela = pd.DataFrame({"palavras":palavras})
tabela

      palavras
0          Ele
1        sabia
2          que
3           eu
4        sabia
5    trabalhar
6          com
7           IA
8            e
9        sabia
10         que
11          eu
12      estava
13   estudando
14  tecnologia
15       sabia
16   trabalhar

In [11]:
tabela["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

      palavras proxima_palavra
0          Ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia       trabalhar
5    trabalhar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia       trabalhar
16   trabalhar            None

In [12]:
tabela = tabela.dropna()
tabela

      palavras proxima_palavra
0          Ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia       trabalhar
5    trabalhar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia       trabalhar

In [32]:
filtro = tabela ["palavras"] == "eu"
tabela[filtro]

   palavras proxima_palavra
3        eu           sabia
11       eu          estava

In [33]:
tabela [filtro]["palavras"].value_counts()

palavras
eu    2
Name: count, dtype: int64

In [34]:
tabela [filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
sabia     0.5
estava    0.5
Name: proportion, dtype: float64

In [35]:
tabela [filtro]["proxima_palavra"].value_counts().idxmax()

'sabia'

In [37]:
palavras_mais_usadas = tabela ["palavras"].value_counts()

palavras_mais_usadas.head(10)

palavras
sabia        4
que          2
eu           2
Ele          1
trabalhar    1
com          1
IA           1
e            1
estava       1
estudando    1
Name: count, dtype: int64